In [54]:
import requests
import pandas as pd
import locale
import os
from pandas import read_csv
from datetime import datetime, timezone


csv = []

for i in range(2016,2021):
    for j in range(1,13):
        if j == 12:
            url = "https://bollettino.appa.tn.it/aria/opendata//csv/"+str(i)+"-"+str(j).zfill(2)+"-01,"+str(i+1)+"-"+str(1).zfill(2)+"-01/2,4,6,8,9,15,22,23"
        else:
            url = "https://bollettino.appa.tn.it/aria/opendata//csv/"+str(i)+"-"+str(j).zfill(2)+"-01,"+str(i)+"-"+str(j+1).zfill(2)+"-01/2,4,6,8,9,15,22,23"

        response = requests.get(url)
        if response.status_code == 200:
            filename =  "./DataSet_APPA/Download/"+str(i)+"-"+str(j)+".csv"

            with open(filename, "wb") as file:
                file.write(response.content)
                print(url)
                print("File downloaded successfully.")
        else:
            print(url)
            print(response.status_code)

https://bollettino.appa.tn.it/aria/opendata//csv/2016-01-01,2016-02-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2016-02-01,2016-03-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2016-03-01,2016-04-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2016-04-01,2016-05-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2016-05-01,2016-06-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2016-06-01,2016-07-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2016-07-01,2016-08-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2016-08-01,2016-09-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2016-09-01,2016-10-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2016-10-01,2016-11-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2016-11-01,2016-12-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2016-12-01,2017-01-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2017-01-01,2017-02-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2017-02-01,2017-03-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2017-03-01,2017-04-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2017-04-01,2017-05-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2017-05-01,2017-06-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2017-06-01,2017-07-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2017-07-01,2017-08-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2017-08-01,2017-09-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2017-09-01,2017-10-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2017-10-01,2017-11-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2017-11-01,2017-12-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2017-12-01,2018-01-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2018-01-01,2018-02-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2018-02-01,2018-03-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2018-03-01,2018-04-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2018-04-01,2018-05-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2018-05-01,2018-06-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2018-06-01,2018-07-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2018-07-01,2018-08-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2018-08-01,2018-09-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2018-09-01,2018-10-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2018-10-01,2018-11-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2018-11-01,2018-12-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2018-12-01,2019-01-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2019-01-01,2019-02-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2019-02-01,2019-03-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2019-03-01,2019-04-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2019-04-01,2019-05-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2019-05-01,2019-06-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2019-06-01,2019-07-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2019-07-01,2019-08-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2019-08-01,2019-09-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2019-09-01,2019-10-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2019-10-01,2019-11-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2019-11-01,2019-12-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2019-12-01,2020-01-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2020-01-01,2020-02-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2020-02-01,2020-03-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2020-03-01,2020-04-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2020-04-01,2020-05-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2020-05-01,2020-06-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2020-06-01,2020-07-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2020-07-01,2020-08-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2020-08-01,2020-09-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2020-09-01,2020-10-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2020-10-01,2020-11-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2020-11-01,2020-12-01/2,4,6,8,9,15,22,23
File downloaded successfully.
https://bollettino.appa.tn.it/aria/opendata//csv/2020-12-01,2021-01-01/2,4,6,8,9,15,22,23
File downloaded successfully.

In [55]:
dir_path2 = "./DataSet_APPA/Download"
res = []
df = []
for path in os.listdir(dir_path2):
    if os.path.isfile(os.path.join(dir_path2, path)):
        res.append(path)
for file in res:
    df.append(read_csv(dir_path2+"/"+file, sep = ",", index_col=False,encoding='latin-1' ))

In [56]:
APPA_Data = pd.concat(df)
APPA_Data

,Stazione,Inquinante,Data,Ora,Valore,Unità di misura
0,Parco S. Chiara,PM10,2016-01-01,1,107.0,µg/mc
1,Parco S. Chiara,PM10,2016-01-01,2,99.0,µg/mc
2,Parco S. Chiara,PM10,2016-01-01,3,73.0,µg/mc
3,Parco S. Chiara,PM10,2016-01-01,4,70.0,µg/mc
4,Parco S. Chiara,PM10,2016-01-01,5,71.0,µg/mc
...,...,...,...,...,...,...
20087,A22 (Avio),Ossido di Carbonio,2020-10-01,20,0.4,mg/mc
20088,A22 (Avio),Ossido di Carbonio,2020-10-01,21,0.4,mg/mc
20089,A22 (Avio),Ossido di Carbonio,2020-10-01,22,0.3,mg/mc
20090,A22 (Avio),Ossido di Carbonio,2020-10-01,23,0.3,mg/mc
20091,A22 (Avio),Ossido di Carbonio,2020-10-01,24,0.3,mg/mc

In [57]:

APPA_Data = APPA_Data.drop("Unità di misura",axis = 1)
APPA_Data = APPA_Data.dropna()
APPA_Data.drop_duplicates(inplace=True)
APPA_Data

              Stazione          Inquinante        Data  Ora Valore
0      Parco S. Chiara                PM10  2016-01-01    1  107.0
1      Parco S. Chiara                PM10  2016-01-01    2   99.0
2      Parco S. Chiara                PM10  2016-01-01    3   73.0
3      Parco S. Chiara                PM10  2016-01-01    4   70.0
4      Parco S. Chiara                PM10  2016-01-01    5   71.0
...                ...                 ...         ...  ...    ...
20087       A22 (Avio)  Ossido di Carbonio  2020-10-01   20    0.4
20088       A22 (Avio)  Ossido di Carbonio  2020-10-01   21    0.4
20089       A22 (Avio)  Ossido di Carbonio  2020-10-01   22    0.3
20090       A22 (Avio)  Ossido di Carbonio  2020-10-01   23    0.3
20091       A22 (Avio)  Ossido di Carbonio  2020-10-01   24    0.3

[1144606 rows x 5 columns]

In [58]:
APPA_Data['Data'] = pd.to_datetime(APPA_Data['Data'], format="%Y-%m-%d")
APPA_Data['Time'] = APPA_Data['Data'] + pd.to_timedelta(APPA_Data['Ora'], unit="H")
APPA_Data.drop('Data', axis=1, inplace=True)
APPA_Data.rename(columns={'Time': 'Data'}, inplace=True)

APPA_Data

              Stazione          Inquinante  Ora Valore                Data
0      Parco S. Chiara                PM10    1  107.0 2016-01-01 01:00:00
1      Parco S. Chiara                PM10    2   99.0 2016-01-01 02:00:00
2      Parco S. Chiara                PM10    3   73.0 2016-01-01 03:00:00
3      Parco S. Chiara                PM10    4   70.0 2016-01-01 04:00:00
4      Parco S. Chiara                PM10    5   71.0 2016-01-01 05:00:00
...                ...                 ...  ...    ...                 ...
20087       A22 (Avio)  Ossido di Carbonio   20    0.4 2020-10-01 20:00:00
20088       A22 (Avio)  Ossido di Carbonio   21    0.4 2020-10-01 21:00:00
20089       A22 (Avio)  Ossido di Carbonio   22    0.3 2020-10-01 22:00:00
20090       A22 (Avio)  Ossido di Carbonio   23    0.3 2020-10-01 23:00:00
20091       A22 (Avio)  Ossido di Carbonio   24    0.3 2020-10-02 00:00:00

[1144606 rows x 5 columns]

In [59]:
APPA_Data = APPA_Data.reset_index(drop=True)  # Reset the index of the DataFrame

APPA_Data.drop(["Ora"], inplace=True, axis=1)  # Drop the "Ora" column
APPA_Data.set_index("Data", inplace=True)  # Set "Data" as the new index

In [60]:
APPA_Data.Stazione.unique()

array(['Parco S. Chiara', 'Via Bolzano', 'Rovereto', 'Borgo Valsugana',
       'Riva del Garda', 'Piana Rotaliana', 'A22 (Avio)', 'Monte Gaza'],
      dtype=object)

In [61]:
loc = ["Parco S. Chiara","Via Bolzano", "Rovereto","Borgo Valsugana","Riva del Garda","Monte Gaza","Piana Rotaliana","A22 (Avio)"]
Gas = ["PM10", "Ossido di Carbonio", "Biossido di Azoto", "Biossido Zolfo", "Ozono","PM2.5"]


APPA_2 = pd.DataFrame()
APPA_4 = pd.DataFrame()
APPA_6 = pd.DataFrame()
APPA_8 = pd.DataFrame()
APPA_9 = pd.DataFrame()
APPA_15 = pd.DataFrame()
APPA_22= pd.DataFrame()
APPA_23 = pd.DataFrame()



for i in loc:
    for j in Gas:
        supp2 = APPA_Data.loc[APPA_Data.Stazione == i]
        supp3 = supp2.loc[supp2.Inquinante == j]
        if supp3.empty:
            continue
        
        prova3 = pd.DataFrame(data = supp3.Valore.values, columns = [j], index = supp3.index)
        if i == loc[0]:
            if APPA_2.empty:
                APPA_2 = prova3.reset_index()
            else:
                APPA_2 = APPA_2.merge(prova3.reset_index(), how = "outer")
        elif i==loc[1]:
            if APPA_4.empty:
                APPA_4 = prova3.reset_index()
            else:
                APPA_4 = APPA_4.merge(prova3.reset_index(), how = "outer")
        elif i==loc[2]:
            if APPA_6.empty:
                APPA_6 = prova3.reset_index()
            else:
                APPA_6 = APPA_6.merge(prova3.reset_index(), how = "outer")
        elif i==loc[3]:
            if APPA_8.empty:
                APPA_8 = prova3.reset_index()
            else:
                APPA_8 = APPA_8.merge(prova3.reset_index(), how = "outer")
        elif i==loc[4]:
            if APPA_9.empty:
                APPA_9 = prova3.reset_index()
            else:
                APPA_9 = APPA_9.merge(prova3.reset_index(), how = "outer")
        elif i==loc[5]:
            if APPA_15.empty:
                APPA_15 = prova3.reset_index()
            else:
                APPA_15 = APPA_15.merge(prova3.reset_index(), how = "outer")
        elif i==loc[6]:
            if APPA_22.empty:
                APPA_22 = prova3.reset_index()
            else:
                APPA_22 = APPA_22.merge(prova3.reset_index(), how = "outer")
        elif i==loc[7]:
            if APPA_23.empty:
                APPA_23= prova3.reset_index()
            else:
                APPA_23 = APPA_23.merge(prova3.reset_index(), how = "outer")

In [86]:
APPA_2=APPA_2.set_index("Data").sort_index()[:"2020-02-29"]
APPA_4=APPA_4.set_index("Data").sort_index()[:"2020-02-29"]
APPA_6=APPA_6.set_index("Data").sort_index()[:"2020-02-29"]
APPA_8=APPA_8.set_index("Data").sort_index()[:"2020-02-29"]
APPA_9=APPA_9.set_index("Data").sort_index()[:"2020-02-29"]
APPA_15=APPA_15.set_index("Data").sort_index()[:"2020-02-29"]
APPA_22=APPA_22.set_index("Data").sort_index()[:"2020-02-29"]
APPA_23=APPA_23.set_index("Data").sort_index()[:"2020-02-29"]

KeyError: "None of ['Data'] are in the columns"

In [89]:
APPA_2.reset_index().to_csv("./DataSet_APPA/APPA_2_"+loc[0]+".csv", index = True)
APPA_4.reset_index().to_csv("./DataSet_APPA/APPA_4_"+loc[1]+".csv", index = True)
APPA_6.reset_index().to_csv("./DataSet_APPA/APPA_6_"+loc[2]+".csv", index = True)
APPA_8.reset_index().to_csv("./DataSet_APPA/APPA_8_"+loc[3]+".csv", index = True)
APPA_9.reset_index().to_csv("./DataSet_APPA/APPA_9_"+loc[4]+".csv", index = True)
APPA_15.reset_index().to_csv("./DataSet_APPA/APPA_15_"+loc[5]+".csv", index = True)
APPA_22.reset_index().to_csv("./DataSet_APPA/APPA_22_"+loc[6]+".csv", index = True)
APPA_23.reset_index().to_csv("./DataSet_APPA/APPA_23"+loc[7]+".csv", index = True)

In [91]:
#APPA_15.set_index("Data").sort_index()[:"2020-02-29"]
APPA_15

                    PM10 Biossido di Azoto Ozono
Data
2018-01-28 01:00:00  5.0               2.0  84.0
2018-01-28 02:00:00  4.0               3.0  83.0
2018-01-28 03:00:00  4.0               3.0  82.0
2018-01-28 04:00:00  4.0               3.0  82.0
2018-01-28 05:00:00  4.0               3.0  84.0
...                  ...               ...   ...
2020-02-29 19:00:00   10                 9    91
2020-02-29 20:00:00   11                 9    90
2020-02-29 21:00:00   10                 8    88
2020-02-29 22:00:00   13                 8    85
2020-02-29 23:00:00   38                 7    89

[20427 rows x 3 columns]

In [85]:
APPA_15.PM10

Data
2018-01-28 01:00:00    5.0
2018-01-28 02:00:00    4.0
2018-01-28 03:00:00    4.0
2018-01-28 04:00:00    4.0
2018-01-28 05:00:00    4.0
                      ...
2020-02-29 19:00:00     10
2020-02-29 20:00:00     11
2020-02-29 21:00:00     10
2020-02-29 22:00:00     13
2020-02-29 23:00:00     38
Name: PM10, Length: 20427, dtype: object